### PR TITLE
chore: bump deps for security advisories

### PR DESCRIPTION
**Pull request by nfischer**
This bumps `shelljs` and `marked` deps since these are flagged with
security advisories. The shelljs update shouldn't actually affect this
package (it only affects `shell.exec()` usage), but the `marked` bump
includes breaking changes.

I noticed that the latest version of marked has a min node version of
v12, so I added engines.node to your package.json (I also manually
tested this on v12 and it seems to work). Let me know if you want me to
add node v12 to your CI config.

```
$ jq '.engines.node' node_modules/marked/package.json
">= 12"
```

### CODE REVIEW

**Comment by nfischer** [comment]
Btw if there's a way to fix this without changing the min node version, that would be even better. This project is really cool and I'd like to pull this plugin into my project [`n_shell`](https://github.com/nfischer/n_shell), but I want to support node >= 10 for that project (and, would also like to avoid pulling in potential security vulnerabilities, hence this PR).

**Comment by JessieFrance** [comment]
@nfischer thank you Nate for the helpful PR (and for making this project possible with the plugin system at ```ShellJS```)! It was a lot of fun learning about ShellJS plugins. The ```n_shell``` project looks really cool.

I'd love to make ```shelljs-plugin-help``` be useful for ```n_shell```, and I'll try to publish a new ```shelljs-plugin-help``` version to NPM soon (with one other security fix as well), but I'm not fully familiar with all the implications of the node ```engines``` variable. For example, would this package be incompatible with ```n_shell``` (even if it does not give any errors on say node versions 10 and 11)? Could a tool like Babel help to make the node ```engines``` field unnecessary?

**Comment by nfischer** [comment]
The field is generally just advisory: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines. I personally like it for packages I maintain because it reminds me of the node versions my package is actually supposed to support. I actually have some automation to make sure that `package.engines.node` matches up with my CI config so that I can't break the module on the supported versions: https://github.com/shelljs/shelljs/blob/master/scripts/check-node-support.js

In this particular case I bumped the `package.engines` field because `marked` declares it only supports node ">= 12", so I assume `marked` doesn't work on lower node versions (which would mean your package wouldn't work on lower versions either). I didn't manually verify this though, so it's always possible your use cases actually do work on node v10 or something like that.

**Comment by nfischer** [comment]
Screenshot from 2022-01-16 18-03-53

Btw in case you're curious, here's what the project looks like integrated into `n_shell` (I'm running it from a local branch). I configured some tricks with REPL inspection to get the return values to stringify nicely for ShellJS commands. I was excited to see the inspection tricks worked out of the box with your plugin too :sunglasses:

**Comment by JessieFrance** [comment]
I'm really happy that it worked! Thank you for showing that, and also for the helpful information on on the ```package.engines``` field.

**Pull request merged**
